### ISSUE TITLE
iconv behaviour unreliable 

### ISSUE THREAD

**Issue by muzzwood** [jfcherng/php-mb-string#2]
Hi! 

I've been building a CMS versioning system using your excellent `php-diff` library which of course has `php-mb-string` as a dependency.
It turns out that it works on some server environments, and not others due to it's usage of `iconv` to convert encoding to UTF-32.
https://github.com/jfcherng/php-mb-string/blob/master/src/MbString.php#L361

e.g. locally `\iconv('UTF-8', 'UTF-32', 'This is a string.')` outputs the expected string. However, on some hosting providers this returns `false`.

In a perfect world we could control the server environments it gets installed on, but often it's not the case. 😅 

Is there any chance of switching to something like `mb_convert_encoding` instead of `iconv`?

**Comment by jfcherng** [comment]
Is there a docker image that I can do test? I am fine to use `mb_convert_encoding` as a fallback. I thought that `iconv` is more generally available than the `mbstring` extension.

**Comment by jfcherng** [comment]
Can you test ef8926ff849863bfea234e99ee827947bedd86b0 ?

**Comment by muzzwood** [comment]
Sorry for the delay getting back to you!
Just tested the commit and it works perfectly. 🎉 

Thanks a bunch for looking into that.

**Comment by jfcherng** [comment]
OK thanks. I've made a new release.

**Comment by jfcherng** [comment]
Hi @brianteeman, I think you will be interested in this since Joomla! has many users for different environments.

**Comment by brianteeman** [comment]
Thanks for the heads up. I need to check but I think we have a hard requirement of iconv
